### ISSUE TITLE
How can I add custom fonts in my editor? I am using version 1.3.3

### ISSUE THREAD

**Issue by jenish064** [gtgalone/react-quilljs#98]

**Comment by Shoulao** [comment]
I believe you can do it the same way as in the original Quill implementation:

```
const listOfFonts = ["Arial", "Courier One", ...]

export const FontAttributor = Quill.import("formats/font");
FontAttributor.whitelist = listOfFonts

Quill.register({
  "formats/font": FontAttributor
});

useQuill({ formats: [ "font" ] })
```

```scss
.ql-font-Arial {
  font-family: Arial, sans-serif;
}
.ql-font-Georgia {
  font-family: Georgia, serif;
}
.ql-font-Courier-New {
  font-family: "Courier New", monospace;
}
```
